### ISSUE TITLE
windows cmake compatibity

### ISSUE THREAD

**Issue by gengjiawen** [bnoordhuis/v8-cmake#13]
Failed run on vs2019 community version.
Related: https://gitlab.kitware.com/cmake/cmake/issues/17532.

**Comment by bnoordhuis** [comment]
I can't access that link but is it related to #10?

**Comment by gengjiawen** [comment]
Sorry, pasted the wrong link, updated.

It's a different issue.

**Comment by bnoordhuis** [comment]
Ah, okay. I'm afraid I don't have a suggestion on how to fix that. `ASM` is needed because `mksnapshot` writes out the snapshot as an assembly file, `embedded.S`.

Pull request welcome, of course, if you manage to figure it out.

**Comment by gengjiawen** [comment]
the link provide a fix. I will raise a PR later.
