### ISSUE TITLE
link error use .a files on ubuntu

### ISSUE THREAD

**Issue by zhwaaaaaa** [bnoordhuis/v8-cmake#23]
I executed `cmake && make` and got some *.a files, and copied these files to /usr/local/v8/lib.
I use the *.a file to build a executable file.
`g++ main.cpp -I/usr/local/v8/include -L/usr/local/v8/lib -lv8_base_without_compiler -lv8_compiler -lv8_snapshot -lv8_inspector -lv8_libplatform`
got so much error message.
......
/usr/bin/ld: /usr/local/v8/lib/libv8_libplatform.a(trace-object.cc.o): in function `v8::platform::tracing::TraceObject::Initialize(char, unsigned char const*, char const*, char const*, unsigned long, unsigned long, int, char const**, unsigned char const*, unsigned long const*, std::unique_ptr<v8::ConvertableToTraceFormat, std::default_delete<v8::ConvertableToTraceFormat> >*, unsigned int, long, long)':
trace-object.cc:(.text+0x73): undefined reference to `v8::base::OS::GetCurrentProcessId()'
/usr/bin/ld: trace-object.cc:(.text+0x83): undefined reference to `v8::base::OS::GetCurrentThreadId()'

**Comment by bnoordhuis** [comment]
You're missing `-lv8_libbase`. It should come last because the other libraries depend on it.

Linking should get a whole lot easier once #14 is implemented.

**Comment by zhwaaaaaa** [comment]
I resolved it with  `-lv8_base_without_compiler -lv8_compiler -lv8_snapshot -lv8_inspector -lv8_libplatform -lv8_libbase -lv8_base_without_compiler  -lpthread` .
and I combined them to monolith with command `ar x *.a && ar crs libv8.a *.o`.  it works.
Thank you.
