### ISSUE TITLE
v8-i18n-support issue

### ISSUE THREAD

**Issue by hejian1639** [bnoordhuis/v8-cmake#39]
```
You have called ADD_LIBRARY for library v8-i18n-support without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at CMakeLists.txt:154 (target_link_libraries):
  Object library target "v8-i18n-support" may not link to anything.
```

I got this issue on ubuntu 18 , when cmake runs, it works on my MacBook

**Comment by bnoordhuis** [comment]
Are you passing `-DV8_ENABLE_I18N=ON` to cmake? i18n builds aren't working yet, pending resolution of #4.

**Comment by hejian1639** [comment]
```
cmake -DCMAKE_BUILD_TYPE=Debug 
```
above is my arguments and I tried -DV8_ENABLE_I18N=ON/OFF both, still same result ...

**Comment by bnoordhuis** [comment]
I'm afraid I can't reproduce. My best guess it's a cmake incompatibility. I'm testing with cmake 3.16.3.

**Comment by hejian1639** [comment]
yes, I guess so , I use latest cmake , it works now. 
thank u.

**Comment by bnoordhuis** [comment]
Glad to hear it's working now. I'll close the issue.
