### ISSUE TITLE
Generating builtins-generated => The system cannot execute the specified program.

### ISSUE THREAD

**Issue by petebannister** [bnoordhuis/v8-cmake#42]
I have a hunch that this is due to the command line getting too long?  Possibly only a Windows issue building from a long sub-path.  And by long I don't mean all that long at all really - perhaps 20 chars.
One build I did actually succeeded and then had unresolved externals linking mksnapsot.  I guess it would be luck of the draw as to where MAX_PATH and any whitespace in the commandline intersect..

In any case it looks like it is a problem that will only get worse.  And this stage of the build could presumably run multiple instances of torque in parallel to avoid the bottleneck here.

**Comment by gengjiawen** [comment]
Same issue, the CI works good, not sure why.

**Comment by bnoordhuis** [comment]
CI builds in `D:/a/v8-cmake/build` which is probably _just_ short enough to avoid the issue.

**Comment by petebannister** [comment]
This was quite a while ago now, but if IIRC, multiple files are passed to torque in one go.  Perhaps this could be divided up and maybe even parallelized in the process - I think it was maxing out only one core on my system.   But as I said this was a long time ago so I could be mistaken!!

**Comment by Jamlee** [comment]
Same issue

**Comment by technyon** [comment]
Any update on this? The windows build is completely broken like this, and there's already a pull request.

**Comment by ScSofts** [comment]
I think I found some solutions.
1.  Clone your project in a shorter path
2.  [Enable Long Paths in Windows 10, Version 1607, and Later](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd)
3.  Use an older version of v8-cmake

**Comment by kingdevnl** [comment]
Is there any other fix for this instead of having to use an older version? 
I don't think for OSS it would be great to ask people to run a reg patch file to build a project.
