### ISSUE TITLE
Is DLL output supported on Windows?

### ISSUE THREAD

**Issue by tedyyu** [bnoordhuis/v8-cmake#46]
I use this repo with VS 2019 and successfully build V8.
Question: I only saw v8.lib as x64 static library in the release folder, without *.dll. This is proved by opening V8.sln in VS2019 because the Configuration Type of the project properties are set to "Static Library".
How can we get dynamic library? Any option to achieve that?

Additional question: I saw by default it's x64. Is it possible to get x86 as well?

**Comment by bnoordhuis** [comment]
> How can we get dynamic library?

Untested but changing all `add_library(foo STATIC ...)` instances to `add_library(foo SHARED ...)` is probably all that's needed.

> Is it possible to get x86 as well?

Maybe - I don't know if the x86 build works, it's definitely untested. You'll need to tweak the variables here:

https://github.com/bnoordhuis/v8-cmake/blob/9075563eaf7476ea22f3642f6fc5336594a5eb2e/CMakeLists.txt#L53-L65

**Comment by tedyyu** [comment]
Thanks, will try.

Can it be tweaked to support ICU?

**Comment by bnoordhuis** [comment]
I wouldn't call that a tweak, V8's i18n build is pretty involved. #4 is the tracking issue.
