### ISSUE TITLE
run  "cmake:debug"  directive,but show "c++: internal compiler error Killed (program cc1plus)"

### ISSUE THREAD

**Issue by RalapChen** [bnoordhuis/v8-cmake#47]
I'm going to run the instructions on vscode.  Running to 14%, there is an error, but I don't know how to solve it, can you help to solve it? 
I think the execution command may be too long, but I do not know how to solve it. Thank you for your.
The error pattern is as follows.
![image](https://user-images.githubusercontent.com/23256312/132460782-75e04d04-44d9-418a-9775-aafb7882305b.png)

**Comment by RalapChen** [comment]
error info:

[build] FAILED: /usr/bin/c++  -DV8_CONCURRENT_MARKING -DV8_HAVE_TARGET_OS -DV8_OS_WINX64 -DV8_TARGET_ARCH_X64 -DV8_TARGET_OS_LINUX -I. -I../v8 -Igenerated -g   -fno-exceptions -std=gnu++14 -MD -MT CMakeFiles/v8_compiler.dir/v8/src/compiler/js-heap-broker.cc.o -MF CMakeFiles/v8_compiler.dir/v8/src/compiler/js-heap-broker.cc.o.d -o CMakeFiles/v8_compiler.dir/v8/src/compiler/js-heap-broker.cc.o -c ../v8/src/compiler/js-heap-broker.cc
[build] c++: internal compiler error: Killed (program cc1plus)
[build] Please submit a full bug report,
[build] with preprocessed source if appropriate.
[build] See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1
[main] Failed to prepare executable target with name 'undefined'

**Comment by bnoordhuis** [comment]
That internal compiler error almost certainly means the compiler needed too much memory and was killed by the kernel's oom killer. You should find a note in the output of `dmesg`.

**Comment by RalapChen** [comment]
Where is the log of dmesg?

**Comment by RalapChen** [comment]
> That internal compiler error almost certainly means the compiler needed too much memory and was killed by the kernel's oom killer. You should find a note in the output of `dmesg`.

It is up and running, thank you.
What do I do next after the run is successful

![image](https://user-images.githubusercontent.com/23256312/132619347-cc965c9c-b62f-4f68-9417-942dc45944dd.png)

**Comment by RalapChen** [comment]
I know how to use it. I can debug it successfully. Thank you


![image](https://user-images.githubusercontent.com/23256312/132628464-a4a102fd-02d8-4cdf-afc7-b19f84abd460.png)

**Comment by RalapChen** [comment]
I know how to use it. I can debug it successfully. Thank you

![image](https://user-images.githubusercontent.com/23256312/132628513-75587568-96dc-4096-ac49-4e2c6592915f.png)
