### ISSUE TITLE
v8-cmake fails to build torque

### ISSUE THREAD

**Issue by securitydweller** [bnoordhuis/v8-cmake#67]
Been trying to build torque, however it always fails with `The system cannot execute the specified program`.

I tried enabling windows long paths and older versions (v.8.9 and v.8.8), still fails.

```
...
C:/src/out/dev/vendor/v8-cmake/torque-generated/objects-printer-tq.cc C:/src/out/dev/vendor/v8-cmake/torque-generated/objects-printer.cc 
  vendor\v8-cmake\CMakeFiles\aggregate-error-tq-csa.cc-851e72b.bat 617396520723a9cb
  The system cannot execute the specified program.
  
  Batch file failed at line 4 with errorcode 1
  
  ninja: build stopped: subcommand failed.
```

**Comment by bnoordhuis** [comment]
We hit the same issue on CI while trying to upgrade V8 earlier this week. Cause unclear, unfortunately.

**Comment by gengjiawen** [comment]
> Been trying to build torque, however it always fails with `The system cannot execute the specified program`.
> 
> I tried enabling windows long paths and older versions (v.8.9 and v.8.8), still fails.
> 
> ```
> ...
> C:/src/out/dev/vendor/v8-cmake/torque-generated/objects-printer-tq.cc C:/src/out/dev/vendor/v8-cmake/torque-generated/objects-printer.cc 
>   vendor\v8-cmake\CMakeFiles\aggregate-error-tq-csa.cc-851e72b.bat 617396520723a9cb
>   The system cannot execute the specified program.
>   
>   Batch file failed at line 4 with errorcode 1
>   
>   ninja: build stopped: subcommand failed.
> ```

Don't use Ninja on MSVC, it's buggy. default should be fine.
