### ISSUE TITLE
Freezes system when building with gcc 11.2.0 on live Linux session

### ISSUE THREAD

**Issue by guest271314** [bnoordhuis/v8-cmake#86]
I'm running a live Linux session on a temporary file system in RAM. How much disk space is needed to build this?

After `make -j8` I get to 1% of the build then system freezes, have to reboot after that.

**Comment by bnoordhuis** [comment]
Gigabytes and gigabytes. Depending on what you build and how you build it, anywhere between 10 and 50 GB.

**Comment by guest271314** [comment]
I'm trying to build `d8`, first as a test run, then incorporating basic C++ to read standard input to get around `readline()`'s deficiencies.

I would consider placing a note in the README about roughly how much space is needed to build this.
