### ISSUE TITLE
Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by HuangPichao** [bnoordhuis/v8-cmake#9]
When I use it to complie V8，I got an error like this:
You have called ADD_LIBRARY for library v8-i18n-support without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at CMakeLists.txt:147 (target_link_libraries):
  Object library target "v8-i18n-support" may not link to anything.

-- Configuring incomplete, errors occurred!
See also "/home/qbxxzd/build/CMakeFiles/CMakeOutput.log".
See also "/home/qbxxzd/build/CMakeFiles/CMakeError.log".

How can I do ?

**Comment by bnoordhuis** [comment]
To be honest, I'm not sure why your cmake is complaining about that. The definition of v8-i18n-support is here:

https://github.com/bnoordhuis/v8-cmake/blob/81322c03f6104b3bedb5fe9de06224802ba155f8/CMakeLists.txt#L122-L152

As you can see it's definitely not empty.

Did you turn on the V8_ENABLE_I18N build option? Try turning it off.

**Comment by bnoordhuis** [comment]
Closing due to lack of follow-up. Let me know if you still want to pursue this.
